dataSources:
  ds_master: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_master?useSSL=false
    username: root
    password: 123456
  ds_slave0: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_slave0?useSSL=false
    username: root
    password: 123456
  ds_slave1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_slave1?useSSL=false
    username: root
    password: 123456
masterSlaveRule:
  name: ds_master_slave
  masterDataSourceName: ds_master
  slaveDataSourceNames: [ds_slave0, ds_slave1]
  props:
    sql.show: true
    configMap:
      key1: value1