spring:
  application:
    name: framework-uid
server:
  port: 8888
leaf:
  port: 6666
  minWorkerThreads: 10
  maxWorkerThreads: 100
  zk:
    port: 2181
    servers:
      - "localhost"
    root: "/leaf-server"
    persistent: "/leaf-server-forever"
    ephemeral: "/leaf-server-ephemeral"
    sessionTimeoutMs: 20000
    connectionTimeoutMs: 15000
    retryTimes: 20
    retryIntervalMs: 1000
    retryIntervalceilingMs: 30000
    heartbeatIntervalMs: 3000
    averageTimestampThreshold: 5000
